services:
  - type: web
    name: django-app
    env: python
    region: frankfurt
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: django-postgres
    region: frankfurt
    plan: free
    ipAllowList: [] 